version: "3.7"
services:
   wordpress:
     image: wordpress:5.0.3
     container_name: "wordpress-php-apache"
     volumes:
       - ./:/var/www/html
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: 192.169.0.10:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
networks:
  default:
    external:
      name: cluster