version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: "mysql-db"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
networks:
  default:
    external:
      name: cluster
  