version: "3.7"
services:
  php-apache:
    image: "adrianharabula/php7-with-oci8"
    container_name: "php7-oci8"
    volumes:
      - ./:/var/www/html
    # depends_on:
    #   - mysql
    restart: always
    ports:
      - "8080:80"
#   mysql:
#     image: mysql:5.7
#     container_name: "api-mysql"
#     environment:
#       MYSQL_ROOT_PASSWORD: "root"
#       MYSQL_DATABASE: "directus"
# #    volumes:
# #      - ./volumes/mysql:/var/lib/mysql
#     restart: always
#     expose:
#       - "3306"
networks:
  default:
    external:
      name: cluster